#!/usr/bin/env sh

if [ $# -eq 0 ]; then
	F=$(fdfind --type f --hidden --exclude ".git" | fzf --scheme=history)
else
	F=$1
fi

if [ -S .yvim.sock ]; then
	nvim --server $(pwd)/.yvim.sock --remote $F
else
	nvim --listen $(pwd)/.yvim.sock $F
fi
