#!/usr/bin/env sh

if [ $# -eq 0 ]; then
	F=$(fdfind --type f --hidden --exclude ".git" | fzf --scheme=history)
else
	F=$1
fi

# TODO: if nothing selected, exit
# TODO: add option to clear stale sock files

curr_dir=$(pwd)
tmp_dir="/tmp/"
socket_fname=$tmp_dir$(echo $curr_dir | tr '/' '_').yvim.sock

if [ -S $socket_fname ]; then
	nvim --server $socket_fname --remote $F
else
	nvim --listen $socket_fname $F
fi
